### ISSUE TITLE
Mouse pointer bearing

### ISSUE THREAD

**Issue by clwgh** [alkissack/Dump1090-OpenLayers-html#16]
Thanks for your recent updates, lots of new features to play with. Much appreciated. It looks great. Currently testing the range plot export and import. Seeing if I can automate a scp to send the downloaded files back into the backup directory on the Pi. I don't think the front-end can do that directly itself due to standard browser security setups these days.

__This issue__

Not really an issue, another enquiry. On the map, the mouse pointer's lat, lon and distance to the site (in the chosen units) is present in the upper left and updates in real time.

I wondered, might it be possible to also add the bearing relative to the site please? ie 000° to 359°. That gives an accuracy of ~4 NM per degree at a range of 220 NM when moving tangentially to the site. Should be accurate enough for this context.

The reason being that it's very useful when combined with the range plot. For example, I see a large spike increase in range in one particular direction. It appears to correlate with a gap between houses. I'd like to see the exact bearing by moving my mouse over it, and then use a compass here to confirm if the gap is indeed responsible.

Another example is moving to a distant aircraft of interest which may be visible with binoculars or a scope. Confirm the bearing on the map, duplicate with a compass and this greatly assists in locating the aircraft visually, rather than trying to guesstimate the direction.

Just an idea, no worries if it's not feasible or a ton of work. Many thanks.

Chris

**Comment by clwgh** [comment]
Sorry to disturb, I just noticed the bearing is already displayed and I never noticed it. Closing.

**Comment by alkissack** [comment]
note re: Currently testing the range plot export and import.
This has limited granularity (1 degree) and as such is not a 100% solution at this point as there may be a max range at the half-degree point (for example) that can be lost.  I hope it provides an improvement over what was before until I can get a more complete solution.

**Comment by clwgh** [comment]
Understood. It looks like the range plot is stored as tables of data in localStorage. If I saved the values of `[Max|Mid|Min]Rng[Lat|Lon|Range]`, ie all 9 entries from the browser (maybe there is a plugin that can do that, or once can do it manually via the developer tools), would that not capture everything needed to recreate the plots perfectly?

Is it possible for the back-end to save this data and present it to the browser as a layer, instead of a browser instance calculating it? I guess it would need a 'virtual' browser running on the PiAware looking at the data and performing the range calcualtions, but now saving the values to a database or something?
