### ISSUE TITLE
Terrain maps not loading, NXDOMAIN

### ISSUE THREAD

**Issue by clwgh** [alkissack/Dump1090-OpenLayers-html#18]
Thankyou for your recent updates to this project.

This issue relates to the map options in the drop-down for "Terrain" and "Terrain + Roads". These options are resulting in a blank canvas with just the aircraft and range, etc overlaid. In otherwords, the map parts are not loading.

Further investigation reveals that the tiles are being loaded from subdomains which apparently do not exist. For example one of the tiles:

![no-tiles](https://github.com/alkissack/Dump1090-OpenLayers-html/assets/115202757/baa8a607-1e11-4e60-9998-aa91227d3741)

```
$ nslookup a.tile.stamen.com
** server can't find a.tile.stamen.com: NXDOMAIN
```

Edit – it looks like this is responsible

https://stamen.com/stamen-x-stadia-the-end-of-the-road-for-stamens-legacy-map-tiles/

Edit 2 – It looks like there is no way for you to make the new service available en masse since it requires an API key or domain auth (I may be wrong on that and it can still be done). Perhaps the code can be [updated to use the new service](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/) and users instructed to create their own accounts and obtain an API key if they want to use it ([free for 200,000 credits](https://stadiamaps.com/pricing/)), and `config.js` updated to store the key, eg `stadiaKey = xxx ;`.

**Comment by alkissack** [comment]
I think this: "Perhaps the code can be [updated to use the new service](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/) and users instructed to create their own accounts and obtain an API key" will likely be required and I'll take a look

**Comment by alkissack** [comment]
Added a free terrain from Stamen Maps - comments welcome (as I dont really use the terrain map)

**Comment by clwgh** [comment]
Thanks for looking at it. Running now and it works fine with the free terrain map, so this will be okay to use for hobby use (as long as there are no impacts to you if activity relates to an account you are using for this).
